### ISSUE TITLE
Conflict between positional encoding and data packing

### ISSUE THREAD

**Issue by thi3nnq** [MeetKai/functionary#106]
@musabgultekin  Thank you for your excellent work. I have a question, can you estimate the impact of data packing on model performance compared to not using data packing? Because I think using such data packing conflicts with the model's architecture, specifically Rotary Embedding.

**Comment by khai-meetkai** [comment]
@thi3nnq 
The performance is expected to be the same, the packing makes sure that: Given data point A and data point B
Loss(A) + loss(B) = loss(packed(A, B))
And there are no conflicts with the model's architecture. In Rotary Embedding, the hidden representation of token is decided by the **token embedding** and the **relative distance between other tokens in the data point**, **not the absolute position embedding** (**_note that in ROPE embedding, they don't add: token embedding and postional embedding_**). You can read more about Rotary Embedding from here: https://blog.eleuther.ai/rotary-embeddings/

**Comment by thi3nnq** [comment]
Oh, thanks so much!
