### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by rgbkrk** [MeetKai/functionary#117]
Hey all! 👋 

I've been using functionary with an on-demand notebook model that allows for the creation and running of jupyter notebook cells. On the small version of the model I've noticed some strange behaviors that I've had to correct. Maybe this is better with the medium model, but I'm curious if you'd be open to some datasets for computational work. What's the format you'd like for future revisions of the model?

**Comment by musabgultekin** [comment]
Hey Kyle!
It's exactly the same as OpenAI fine-tuning format. 
JSONLines file.
Each line contains a single conversation
Each conversation has:
- messages
- tools

**Comment by musabgultekin** [comment]
What kind of strange behaviors have you noticed?
