### ISSUE TITLE
Please correct the Readme regarding requirements and installation

### ISSUE THREAD

**Issue by stippi** [MeetKai/functionary#120]
This is such a pain. I still have not managed to get a working installation. You link to "PyTorch" as the first step. Well actually, vLLM requires Python 3.11, and not the current version of Python. That's where it begins. vLLM then uses a fixed version of torch which is 2.1.2, but python 3.12 doesn't see that version as available. So first things first:

- Tell users that they have to use Python 3.11
- They need to  install the correct PyTorch version. For my Windows system with CUDA 12.3.0, that is this line:
```shell
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
```
- Also, cargo and rust need to be installed for whatever reason, it's used by a pip sub-process.
- And for some reason, `numpy` has to be installed manually before, as it seems it's not mentioned in the requirements of whatever needs it.

Sorry, if I sound frustrated, but I've been trying all day to get a working install, and I have a 16MBit Internet connection and torch alone is 2.5GiGs. I have not figured out how to use cached downloads or even continue when downloads are interrupted.

**Comment by musabgultekin** [comment]
Hi, so sorry for that issue. I thought just linking the vLLM installation would be sufficient.

We generally test it with python 3.10 and it works properly. I'll add that requirement to the README now

**Comment by musabgultekin** [comment]
Added the requirements link: https://github.com/MeetKai/functionary/pull/121

**Comment by musabgultekin** [comment]
Cargo and Rust is not needed. What type of error are you getting regarding to rust&cargo?

**Comment by stippi** [comment]
Looking again at the vLLM installation [requirements](https://docs.vllm.ai/en/latest/getting_started/installation.html#requirements), I now see "OS: Linux". How did I miss that before?! I guess it can't work on Windows, then.

The Cargo and Rust thing may have been from trying to build vLLM (trunk) from source.
