### ISSUE TITLE
Support function_call parameter

### ISSUE THREAD

**Issue by christobill** [MeetKai/functionary#13]
Hello :wave:,
Thank you for this awesome repo

It looks like the `function_call` is not implemented (or the model hasn't been finetuned with it)
Example:
```
import openai

openai.api_key = "" # We just need to set this empty so it works with openai package. No API key is required.
openai.api_base = "http://localhost:8000/v1"

openai.ChatCompletion.create(
    model="musabgultekin/functionary-7b-v1",
    messages=[{"role": "user", "content": "What is the weather for Istanbul?"}],
    function_call="none",
    functions=[{
        "name": "get_current_weather",
        "description": "Get the current weather",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA"
                },
            },
            "required": ["location"],
        },
    }]
)
```

Give the following result:
```
{
  "id": "b8d5d347-27ac-43bd-b1ea-49aa99eb4bb6",
  "object": "chat.completion",
  "created": 1691280426.4675407,
  "choices": [
    {
      "message": {
        "role": "assistant",
        "content": null,
        "name": null,
        "function_call": {
          "name": "get_current_weather",
          "arguments": "{\n  \"location\": \"Istanbul\"\n}"
        }
      },
      "finish_reason": "stop",
      "index": 0
    }
  ]
}
```

Similar issue with: `function_call={ "name": "a_function_name" }` in a different use case (forcing the function calling).

Is this an issue you consider to tackle?

**Comment by musabgultekin** [comment]
Hello 👋 

Yeah currently the server doesn't support that. But I believe we can do it without finetuning, as it appears something at application level. Cause currently we let model decide if it should call a function or not. and when it decides to call a function, it also decides which function to call. If we prepend that, we can essentially force the model to do those. I've added this to the roadmap.

https://github.com/musabgultekin/functionary/pull/14

Should not be too hard. Thanks!

**Comment by unaidedelf8777** [comment]
definetly should not be hard. to make a function call mandatory, we could just use Microsoft guidance. thus avoiding fine-tuning.

**Comment by jeffreymeetkai** [comment]
Hi, we have implemented `tool_choice` for our suite of v2 models. However, `function_call` was not implemented as both OpenAI and us are looking at deprecating `functions` in OpenAI-Python v0 and functionary v1.4 models respectively. Feel free to try `tool_choice` with our latest v2.2 medium and small models (they are much more intelligent than v1.4)!

I will be closing this issue now. Thank you.
