### ISSUE TITLE
Packing without FA

### ISSUE THREAD

**Issue by IsNoobgrammer** [MeetKai/functionary#132]
How to use non-cross contaminated packing without flash attention , i read in axotol they said using sdpa , but even they are not using sdpa
![image](https://github.com/MeetKai/functionary/assets/112808251/c39f74f9-fa3d-4c20-8399-452135749718)

Also there implementation of packing is different than yours

cc: @khai-meetkai

**Comment by khai-meetkai** [comment]
Hi @IsNoobgrammer, Flash Attention is becoming more popular because it is faster, consumes less memory during training, so we **don't focus on making packing without cross-contamination work without Flash Attention**. Thank you for your interest!

**Comment by jeffreymeetkai** [comment]
Thank you once again. Will be closing this issue now but feel free to reopen if you still have questions.
