### ISSUE TITLE
Is it possible to use quantized model with vLLM?

### ISSUE THREAD

**Issue by remiconnesson** [MeetKai/functionary#133]
Hello,

I tried to use https://huggingface.co/meetkai/functionary-small-v2.2-GGUF/tree/main the `functionary-small-v2.2.q4_0.gguf` with vLLM but it did not work. Is there a special maniplulation I need to do?

I tried:
```pdm run python server_vllm.py  --model "meetkai/functionary-small-v2.2-GGUF" --served-model-name "functionary-small-v2.2.q4_0.gguf" --host 0.0.0.0```
and other variations but none worked;

There's an error
```
OSError: meetkai/functionary-small-v2.2-GGUF does not appear to have a file named config.json. Checkout 'https://huggingface.co/meetkai/functionary-small-v2.2-GGUF/main' for available files.
```

Is it something that is possible?

**Comment by jeffrey-fong** [comment]
Hi, unfortunately, vLLM does not work with GGUF models as of now. You should use llama.cpp to perform inference on the functionary GGUF models. We have recently integrated functionary models directly into llama-cpp-python. [Here's](https://github.com/MeetKai/functionary?tab=readme-ov-file#llamacpp-inference) how you can use it.

**Comment by themrzmaster** [comment]
I've converted medium to AWQ https://huggingface.co/luccazen/functionary-medium-v2.2-awq
just use with the vllm script using --quantization awq

**Comment by jeffreymeetkai** [comment]
Thank you @themrzmaster for pointing this out. We are also considering to release AWQ weights as part of future releases currently, starting from the latest v2.4 [here](https://huggingface.co/meetkai/functionary-small-v2.4-AWQ).

Anyway, I will be closing this issue now. Feel free to reopen if you have questions.

**Comment by remiconnesson** [comment]
> Thank you @themrzmaster for pointing this out. We are also considering to release AWQ weights as part of future releases currently, starting from the latest v2.4 [here](https://huggingface.co/meetkai/functionary-small-v2.4-AWQ).
> 
> Anyway, I will be closing this issue now. Feel free to reopen if you have questions.

Wow amazing, thank you for the heads up :)
