### ISSUE TITLE
The model determines when to execute functions, whether in parallel or serially.

### ISSUE THREAD

**Issue by ShubhamVerma16** [MeetKai/functionary#137]
Hi

I wanted to understand how does the model understand on the mentioned points:
1. When to execute functions - How does the model decide?? Is it only the key word <pre> tool_choice </pre> or there is any other deciding factor??
2. How does the model decide if the function needs to be run in parallel or serially?? is it the training data or what is the deciding factor here???

Thanks in advance for your response and please do let me know if any more details are required from my side.

**Comment by musab-mk** [comment]
Yes, its all in dataset and the model is trained to lean those types of parallel calls and also when to call a function or not call at all.
So in our dataset, there are assistant messages that doesn't call the function when its not required, even though they are provided to the model.
In our dataset, we have all those kind of combinations, thus, the model learns to act based on the user prompt.

**Comment by jeffreymeetkai** [comment]
Thank you for your questions. I will be closing this issue now but feel free to reopen if you have any other questions.
