### ISSUE TITLE
Bug: AssertionError for role "assistant" for OpenAI compatible Server

### ISSUE THREAD

**Issue by morgendigital** [MeetKai/functionary#141]
I'm running the vLLM OpenAI-compatible server and not always, but almost 95% of the time, tool calls are not working, and I'm afraid it's the OpenAI-compatible server code and not the model. 

I tried to debug it and it seems there's an issue with the role assertion. Here's what I found. I'm using functionary-medium-v2.2 and I get the following error on line 92 of _prompt_template_v2.py_:

```
Apr 02 15:49:49 gpuserver1 bash[84168]:   File "/root/functionary/functionary/prompt_template/prompt_template_v2.py", line 92, in convert_message_to_prompt
Apr 02 15:49:49 gpuserver1 bash[84168]:     assert role == "assistant"
Apr 02 15:49:49 gpuserver1 bash[84168]: AssertionError
```

I added `print(role)` at line 81 (in the `convert_message_to_prompt()` function) in _prompt_template_v2.py_ to see what roles it provides me, and this is what I got when a function call was requested by the Chat UI I'm using:

```
Apr 02 15:49:49 gpuserver1 bash[84168]: system
Apr 02 15:49:49 gpuserver1 bash[84168]: system
Apr 02 15:49:49 gpuserver1 bash[84168]: system
Apr 02 15:49:49 gpuserver1 bash[84168]: user
Apr 02 15:49:49 gpuserver1 bash[84168]: function
```

It seems that it is providing a role namend "function", which I think is not something to be expected here I guess?

This is the `print(role)` if I do a normal chit-chat conversation:

```
Apr 02 15:59:27 gpuserver1 bash[84168]: system
Apr 02 15:59:27 gpuserver1 bash[84168]: system
Apr 02 15:59:27 gpuserver1 bash[84168]: system
Apr 02 15:59:27 gpuserver1 bash[84168]: user
Apr 02 15:59:27 gpuserver1 bash[84168]: assistant
Apr 02 15:59:27 gpuserver1 bash[84168]: user
Apr 02 15:59:27 gpuserver1 bash[84168]: assistant
```

And this is a **successful** conversation with a user message where a function call should have been requested (and it worked):

```
Apr 02 16:00:34 gpuserver1 bash[84168]: system
Apr 02 16:00:34 gpuserver1 bash[84168]: system
Apr 02 16:00:34 gpuserver1 bash[84168]: system
Apr 02 16:00:34 gpuserver1 bash[84168]: user
Apr 02 16:00:34 gpuserver1 bash[84168]: assistant
```

As you can see, it shows "assistant" here. The correct function call was triggered here.
What could the issue be here? Is it maybe that _function_ role is not supported by the OpenAI-compatible vLLM Server or not handling it correctly?

Thank you for your help!

**Comment by khai-meetkai** [comment]
Hi @morgendigital Can you show me the example of the input messages that you tested.
However, functionary models are **parallel-tool-calls** so please use **tools** instead of **functions**:
Supported roles: user, system, tool (**not function**). Here is the example: https://github.com/MeetKai/functionary?tab=readme-ov-file#openai-compatible-usage
By the way, we released our newest model: V2.4 that is more accurate: https://huggingface.co/meetkai/functionary-medium-v2.4 than v2.2

**Comment by morgendigital** [comment]
Hi @khai-meetkai - thank you for your message! Yes I can show you the input - it's possible that the software we used to test it wanted to do it the old function calling way (via _functions_ instead of _tools_), I will verify that. Thank you.

**Comment by jeffreymeetkai** [comment]
Hi @morgendigital , firstly, all our v2 models support _tool_ role only. Secondly, in your input, the _function/tool_ turn must only be after an assistant turn as the tool turn is supposed to return the output of the tool called by the assistant in the previous turn. Thus, your input is wrong in this case (maybe you forgot to add the assistant tool-call turn prior to that tool turn?) and triggered that assertion error.

Hope this helps!
