### ISSUE TITLE
Functionary 2.4 Medium running locally: Tool call returns both 'function_call' and 'tool_calls'

### ISSUE THREAD

**Issue by ChristianWeyer** [MeetKai/functionary#156]
Hey!

my hardware config: Apple MBP M3 Max with 128GB.
I am running 2.4 Medium like this:

`python3 -m llama_cpp.server --model "/Users/christianweyer/.cache/lm-studio/models/functionary/functionary-medium-v2.4.Q8_0.gguf" --chat_format functionary-v2 --hf_pretrained_model_name_or_path "/Users/christianweyer/.cache/lm-studio/models/functionary" --n_gpu_layers -1`

All looks fine so far.

Now, when I submit this `curl` command (from the Open AI API doc page):

``` bash
curl http://localhost:8000/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}' | json_pp
```

... I get back this from _Functionary_:

``` json
{
   "choices" : [
      {
         "finish_reason" : "tool_calls",
         "index" : 0,
         "logprobs" : null,
         "message" : {
            "content" : null,
            "function_call" : {
               "arguments" : "{\"location\": \"Boston\", \"unit\": \"fahrenheit\"}",
               "name" : "get_current_weather"
            },
            "role" : "assistant",
            "tool_calls" : [
               {
                  "function" : {
                     "arguments" : "{\"location\": \"Boston\", \"unit\": \"fahrenheit\"}",
                     "name" : "get_current_weather"
                  },
                  "id" : "call_LS3eRmRihx0jR0SnV28CPFrs",
                  "type" : "function"
               }
            ]
         }
      }
   ],
   "created" : 1712940465,
   "id" : "chatcmpl-8729ff89-5b88-45b0-924f-6b2d83796d64",
   "model" : "/Users/christianweyer/.cache/lm-studio/models/functionary/functionary-medium-v2.4.Q8_0.gguf",
   "object" : "chat.completion",
   "usage" : {
      "completion_tokens" : 1,
      "prompt_tokens" : 185,
      "total_tokens" : 186
   }
}
```

We should not see `function_call`, but just `tool_calls`.

Thanks @khai-meetkai !

**Comment by jeffreymeetkai** [comment]
Hi @ChristianWeyer , this was the design in the llama-cpp-python integration previously as we wanted a quick integration due to the high popularity of GGUF models among the community. We will further improve the integration in the near future.

For now, both _function_call_ and _tool_calls_ will be generated. In the event of parallel tool calls, _function_call_ will only contain the first tool in the _tool_calls_ list. You can ignore the _function_call_ field for now if you are passing in requests containing _tools_.

**Comment by ChristianWeyer** [comment]
Thank for the quick and comprehensive answer @jeffreymeetkai!

This sounds promising.
... as we all do want to have the most compact answer possible in our LLM inference responses :-).
