### ISSUE TITLE
Update model to Llama3

### ISSUE THREAD

**Issue by jayakumark** [MeetKai/functionary#165]
To catch up with llama3 release, will there be a new model with llam3 as base?

**Comment by jeffreymeetkai** [comment]
Hi, we are currently investigating potentially using llama3. Hope to provide good news soon.

**Comment by julian-passebecq** [comment]
@jeffreymeetkai glad to hear that. could you give a timeline or when you ll give news ? thanks

**Comment by khai-meetkai** [comment]
Hi @julian-passebecq, we have recently released new model based on LLama-3, you can take a look at here: https://github.com/MeetKai/functionary?tab=readme-ov-file#models-available

**Comment by heesuju** [comment]
Hello, 
Is the model based on llama-3 small 2.5?

**Comment by khai-meetkai** [comment]
Hi@heesuju, the [meetkai/functionary-small-v2.5](https://huggingface.co/meetkai/functionary-small-v2.5) was based on llama-3

**Comment by yhyu13** [comment]
Qwen2-7B has reported with SOTA scores among all other models in 7B size : [Qwen2-7B](https://huggingface.co/Qwen/Qwen2-7B#qwen2-7b-performance).

It would be great if next release if based on Qwen2-7B. The only issue is that it is a multilingual model which tends to spit out the most trained language, which requires some prompting techniques to prevent those.

**Comment by jeffrey-fong** [comment]
Hi @yhyu13 , we will consider investigating this base model. Thank you for this suggestion!

**Comment by khai-meetkai** [comment]
Hi @yhyu13, we tried finetuning Qwen2-7B on our dataset, but the result was not as good as with LLama3 on our internal evaluation, so we don't have a plan for releasing that model.
