### ISSUE TITLE
Can I get dataset used for training Functionary 2.4?

### ISSUE THREAD

**Issue by gunpal5** [MeetKai/functionary#172]
Hello

I wanted to train WizardLM-2 8x22b for function/tool calling. It has reasoning capability comparable to GPT-4. If we manage to train it with function calling capabilities like functionary has then we would have an open source alternative to GPT-4.

Can i get access to training dataset used for Functionary medium 2.4? or is it too much to ask for?

Regards,
Gunpal Jain

**Comment by jeffreymeetkai** [comment]
Hi! We don't plan to release the dataset. Thank you for your interest and suggestion!
