### ISSUE TITLE
Question about grammar sampling

### ISSUE THREAD

**Issue by rvsh2** [MeetKai/functionary#181]
Hi,

I manage to run server_vllm.py but I struggle to run it with AWQ model to save memory usage.
I've got 24gb of VRAM and when running quantized AWQ model I got almost 17gb used. It is almost the same amount as when running not quantized model fp16.
I research the VLLM project and found that it is most probably because of vllm bad awq support.

I would like to run functionary using llama_python but has it the same functionality as with server_vllm?

I found that server_vllm runs perfectly, all tools runs as they should and json response is perfect. 
Will I have the same behaviour using llama_python? Does it has also grammar sampling etc.?

Thank you for response.
BR
Krzysztof

**Comment by jeffreymeetkai** [comment]
Hi, in the llama-cpp-python integration, we only constrain the parameters of tool calls by using llama.cpp's JSON GBNF sampler ([more info here](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md)).

The generation of the prompt template and tool names are not constrained. However, we have not encountered any cases before where the model generation did not follow the prompt template so the chances of this happening is very low. The chances of incorrect tool names is fairly low too for v2.4.

**Comment by rvsh2** [comment]
Thank you for explanation. Now I undestand.
