### ISSUE TITLE
Working with Ollama

### ISSUE THREAD

**Issue by rvsh2** [MeetKai/functionary#183]
Hi,

Is there a possibility to use functionary v2.4 small with Ollama? Is there a need for some adjustments to do it?

Thank you.

BR

**Comment by jeffreymeetkai** [comment]
Hi, unfortunately Ollama does not support functionary since Ollama does not contain any function calling features.

The most you can do will be to chat with the model locally following this [guide](https://github.com/ollama/ollama?tab=readme-ov-file#customize-a-model).
