### ISSUE TITLE
LM Studio support?

### ISSUE THREAD

**Issue by ruze00** [MeetKai/functionary#196]
I have my code working with the built-in vLLM model using localhost:8000, but if I try running against the LM Studio server using the `meetkai/functionary-small-v2.5-GGUF/functionary-small-v2.5.Q8_0.gguf` model, it returns text not function calls.

Is it the prompt format?  If so, which prompt format to use with LM Studio?

**Comment by jeffrey-fong** [comment]
Hi, LM Studio's server does not support function-calling. You can refer to #148 for more information on how to work with functionary via handling the raw text prompt and generated response directly.

**Comment by ruze00** [comment]
Thanks for the response.
