### ISSUE TITLE
Support `stream=True`

### ISSUE THREAD

**Issue by rgbkrk** [MeetKai/functionary#2]
Hi 👋 ! I'm really excited to work with the model you've trained.

I've been working on a project called [chatlab](https://pre.chatlab.dev/docs/intro#first-example) which is a wrapper on the openai interface to support function calling and interactivity within a jupyter notebook. This is the general interface:

```python
import chatlab
import random

def flip_a_coin():
    '''Returns heads or tails'''
    return random.choice(['heads', 'tails'])

chat = chatlab.Chat()
chat.register(flip_a_coin)

await chat("Please flip a coin for me")
```

<details style="background:#DDE6ED;color:#27374D;padding:.5rem 1rem;borderRadius:5px">
<summary>&nbsp;𝑓&nbsp; Ran `flip_a_coin`
</summary>
<br />

Input:

```json
{}
```

Output:

```json
"tails"
```

</details>

```markdown
It landed on tails!
```

I built it with `stream=True` by default. I wanted to go ahead and use it with functionary but immediately ran into the issue of the endpoint not accepting the streaming payload. Can this be part of the roadmap? I can adapt for allowing not-streaming but I'd love to be able to use this in streaming mode too.

**Comment by musabgultekin** [comment]
Thanks for the PR, Yeah definitely! I was actually working on it too but left it to prioritize other stuff. 
Added to the roadmap:
https://github.com/musabgultekin/functionary/commit/cc1d5d567f0d6fb8166a99c57c4c5ffe890650bb

**Comment by musabgultekin** [comment]
I checked out your repo too, it looks amazing. 
I was actually thinking about this automatic function calling idea that you implemented already.
When functions don't have type annotations, do you assume they are strings or throw error, i think i didnt get that part

**Comment by rgbkrk** [comment]
Chatlab throws an error if there are no type annotations.

```python
from chatlab import Chat
chat = Chat()

def magic_increment(value):
    '''Returns a bigger number than passed in'''
    return abs(value)*2 + 1

chat.register(magic_increment)
```

```
Exception: Parameter value of function magic_increment must have a type annotation
```

It's probably worth it to try assuming they're strings, though I think the json schema could also be flexible and allow `any`.

```
  "properties": {
    "value": {}
  }
```

I went with explicit because its much easier to work with the model and the function by having explicit types. Otherwise, you have to implement parsing in your chat functions to make sure the model passed in the right arguments.

**Comment by musab-mk** [comment]
Streaming is supported now! with this PR:  https://github.com/MeetKai/functionary/pull/29 
Thanks for the heads up!
