### ISSUE TITLE
Evaluations

### ISSUE THREAD

**Issue by ogencoglu** [MeetKai/functionary#21]
Thanks for the library!

Would be interesting to evaluate functionary with e.g. [AgentBench](https://github.com/THUDM/AgentBench). Any plans of such?

**Comment by musab-mk** [comment]
Hey, yeah we can check that out thanks!

**Comment by musabgultekin** [comment]
Hey, so sorry for that it took way longer than expected :( 

Here are the internal dev set results:
https://github.com/MeetKai/functionary?tab=readme-ov-file#function-prediction-evaluation

**Comment by musab-mk** [comment]
Hey, sorry for late evaluation, it took longer than expected :
