### ISSUE TITLE
How can this api_server running only with CPU?

### ISSUE THREAD

**Issue by dscrlc** [MeetKai/functionary#22]
Unfortunately, my server has 48 CPUs but no GPU. How can I run your program in this situation?

**Comment by musab-mk** [comment]
Hi, this is very late sorry for that :(
But we've just implemented the CPU support

**Comment by sreekanthputta** [comment]
Use this command to run it only with CPU
```python3 server.py --model "meetkai/functionary-7b-v1.1" --device=cpu```
