### ISSUE TITLE
I would like to know how to perform evaluation using the SGD dataset.

### ISSUE THREAD

**Issue by junrae6454** [MeetKai/functionary#221]
I see "Evaluation function call prediction in SGD dataset." listed under the evaluation section. Could you please provide a script to perform the same evaluation?

Thank you!

**Comment by junrae6454** [comment]
@khai-meetkai @jeffreymeetkai 
Could you please take a moment to look into it and provide some feedback or direction?
Thank you very much for your time and assistance.

**Comment by jeffrey-fong** [comment]
Hi, as of now, we have not decided when we will be releasing the data for evaluation. We will inform you when we release the data with the evaluation scripts. Apologies for any inconvenience caused and thank you for the request.
