### ISSUE TITLE
Funtionary vs LLMCompiler

### ISSUE THREAD

**Issue by xdevfaheem** [MeetKai/functionary#227]
Apparently LLMCompiler is extended & optimised version of ReWOO agent architechture with parallel function calling capabilities. It seem's functionary is capable of parallel function calling too. So, what is the core difference between fuctionary and LLMComplier apart from panning steps in LLMC...

Could anyone help me clear this up?

**Comment by xdevfaheem** [comment]
@khai-meetkai ? (Sorry for pinging)

**Comment by khai-meetkai** [comment]
Hi @xdevfaheem, I think the basic difference between function calling models (such as Functionary, gpt-40, ...) and LLM-Compiler is: 
+ LLMCompiler first **generates a plan (A dependency graph) ahead**, then executes functions like traversing all nodes in the graph, each node can be considered as a function call.
+ Function calling models: **do not generate a plan ahead**, just analyze the query and the results of previous function calls to decide if we need to execute more functions or not. It is more like ReAct **except it can execute parallel function calls at each step.**

**Comment by xdevfaheem** [comment]
Yeah, I thought so. Now, you confirmed it. TQSM. 

But in LLMCompiler and ReWOO, After parsing the plan and if there's is any error in execution stage then the agent would fail if there is no replanning stage, but as of now, replanning in LLMCompiler is not efficient and not fault tolerant. I think ReAct still stand tall but functionary is an enhanced version with parallel function calling without fancy thought process prompting. i guess if we add planning and replanning ability to functionary, it would be strainght up lit. (optionally, we can make it stateful agent with fsm lib like xstate).

i guess, i would work on those.
