### ISSUE TITLE
Request for provide more train details

### ISSUE THREAD

**Issue by warjiang** [MeetKai/functionary#23]
when i try to repeat show case in the readme.md, i found cannot repeat the [ Telecommunications - Customer Support
 case](https://github.com/MeetKai/functionary/#telecommunications---customer-support) 
so i want to get more detail for training

**Comment by warjiang** [comment]
If need any help, willing to offer join this project

**Comment by warjiang** [comment]
any more response. when i test api reponse, stop reason may be not right, should not be 'stop' but for 'function_call', like openai


![image](https://github.com/MeetKai/functionary/assets/6478745/899b3626-f09c-4dbf-951a-f895b05b85d0)

**Comment by musab-mk** [comment]
Hey, yeah, finish_reason is wrong as its hardcoded for simplicity. But definitely fixable. In terms of training details, can you kindly expand on what are you exactly asking for? 
Thanks!

**Comment by warjiang** [comment]
> Hey, yeah, finish_reason is wrong as its hardcoded for simplicity. But definitely fixable. In terms of training details, can you kindly expand on what are you exactly asking for? Thanks!

@musab-mk 
We are trying to combined functionary with devops, may be  you can it called AutoDevops. We want to standardize our devops plugins in form of JSON Schema, every plugin has title、description、params just like openai or this repo described. Our scenario is for internal deployment and we don't want to use opanai or Microsoft's cognitive services. Your work has given us great encouragement, and we believe that it is entirely feasible to automate internal operation and maintenance. After test some cases, we found that the scene of multiple rounds of conversation is still much worse than the version provided by openai, although the result may be given directly in the second round of conversation. We want to get more details  of how to prepare dataset and how to train model, looking forwarde for your reply 😀.

**Comment by musabgultekin** [comment]
Hi, it took a very long time for us to make it work properly with the quality of OpenAI models.
Sorry for that: (

But finally we're confident that our evals show that even in multi-turn, we can beat the gpt3.5 models. 
https://github.com/MeetKai/functionary?tab=readme-ov-file#function-prediction-evaluation

As for the training, we documented much better here
https://github.com/MeetKai/functionary/tree/main/functionary/train

**Comment by musab-mk** [comment]
Hi,
