### ISSUE TITLE
Training & validation datasets

### ISSUE THREAD

**Issue by l4b4r4b4b4** [MeetKai/functionary#242]
Are the datasets for training open source as well?
could only find `2023-12-20_train.jsonl` and `2023-12-20_val.jsonl` referenced in the trainign README.md, BUt not the files themselves.

Woudl be great to at least have the validation dataset to use it as calibration dataset for best AWQ quantisation.

**Comment by musabgultekin** [comment]
Hi, we have not open-sourced the datasets and we don't have plans to do at the moment.
