### ISSUE TITLE
Decision process for fn calls

### ISSUE THREAD

**Issue by xdevfaheem** [MeetKai/functionary#245]
I'm very curious about, how functionary model knows when to call a fn or when to chat normally. Before i came to know about functionary, I thought in order do so for my PA agent, i has to incorporate a classifier for every forward pass throught the module.

Is there a aligning process or it's basically thought to do through SFT or how? It would be very helpful if you could share some info about this @khai-meetkai, TQSM.

**Comment by jeffrey-fong** [comment]
Typically, we fine-tune the models using SFT on our own dataset. [Here](https://github.com/MeetKai/functionary/blob/main/functionary/train/README.md) are some details about training, although we haven't update it for the newer base models like Llama3/3.1 yet.

We do not have plans to open-source our dataset and it's creation process currently. Thank you for your understanding.

**Comment by xdevfaheem** [comment]
So it basically trained to when or when not to and how to respond. Great!
