### ISSUE TITLE
Request to check v3-llama3.1.txt for typos

### ISSUE THREAD

**Issue by hexists** [MeetKai/functionary#282]
https://github.com/MeetKai/functionary/blob/fa6384838cc5ff67080b45ce3cdf45e121ff9937/functionary/prompt_template/jinja_templates/v3-llama3.1.txt#L28
```
If a you choose to call a function ONLY reply in the following format:\n<{start_tag}={function_name}>{parameters}{end_tag}\n
```

Hello.
Thank you for the great code.

In the above input, the '<' (less-than) symbol seems to be a typo, am I right?
My guess is that it is a typo because “{start_tag}” is a “<function”.

Thank you for your reply.

**Comment by jeffreymeetkai** [comment]
Hi, thanks for pointing this out! I think it is also a bug from Meta's side as we copied the prompt template from [here](https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_1#user-defined-custom-tool-calling).

We will take this into account for future models if we decide to use this template. Thank again for pointing this out!

**Comment by hexists** [comment]
@jeffreymeetkai 
Thank you for understanding my post.
I appreciate you taking the time to respond. Have a great day.
