### ISSUE TITLE
Possibly a trainer with all your needed features already made.

### ISSUE THREAD

**Issue by unaidedelf8777** [MeetKai/functionary#46]
@musabgultekin  I was goin threw my email saw what y’all have been up to. I figured I would lyk about axolotl which seems to be why you guys are basically building from scratch. If you choose to use it, all you will have to do is include your custom prompt formatting strategy for the function calls, it handles everything else including only calculating loss on assistant responses, and using target tensors, also it has bin packing implemented, which in my experiments speeds up trainings by atleast 3x. 

just figured I would let you know, maybe save you some work. 

https://github.com/OpenAccess-AI-Collective/axolotl

**Comment by musab-mk** [comment]
Hi @unaidedelf8777 Thank you for this! It looks really helpful. We'll check it out!
