### ISSUE TITLE
chat template for the function/messages

### ISSUE THREAD

**Issue by jens-create** [MeetKai/functionary#51]
Hi, is there a jinja template somewhere that shows the chat template that should be used. I would like not to rely too much on vllm/fschat to do the formatting of the messages.

Something akin to `chat_template` in https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/blob/main/tokenizer_config.json

**Comment by musabgultekin** [comment]
Hi! thanks for the PR.

 @khai-meetkai is working on the chat template. https://github.com/MeetKai/functionary/pull/50

**Comment by jens-create** [comment]
@musabgultekin Thanks for the reply - cool!
