### ISSUE TITLE
Context Size

### ISSUE THREAD

**Issue by sashokbg** [MeetKai/functionary#72]
Hello is context size bigger than 4096 possible or is this a hard limit from the original Llama 2 7b model ?
Thank you

**Comment by jeffreymeetkai** [comment]
Hi,

For v1.4 and v2, we use [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1) as our base model. For v1.1, we use [meta-llama/Llama-2-7b](https://huggingface.co/meta-llama/Llama-2-7b). You can provide context size up to the respective model's hard limit.

One thing to note is that we cannot guarantee that the performance will be as good beyond 4k as we have finetuned all our current models up to that length. However, I think the dip should not be a significant one.

There are plans to increase the context length for our future models so stay tuned!

Hope I've answered your questions. Thanks!
