### ISSUE TITLE
Discussions page

### ISSUE THREAD

**Issue by sashokbg** [MeetKai/functionary#76]
Hello, I would like to know where can we have some discussions related to this project that are not necessarily issues ?
Do you have a slack channel or discord ? Or maybe activate Github discussions page ?

I would like to simply share some of my observations on using this model and share knowledge and practices with other people.

Thank you

**Comment by khai-meetkai** [comment]
Hi @sashokbg 
We have already activated the Github discussions page !

**Comment by sashokbg** [comment]
Thank you ! @khai-meetkai
