### ISSUE TITLE
Non Contaminated Packing into trl

### ISSUE THREAD

**Issue by nivibilla** [MeetKai/functionary#98]
Hi, I'm trying to merge your custom non packing implementation into trl. And I'm facing some issues in getting it to work. is it possible to use the packedDataset class alone without having to merge all your code into trl?

Please look at my [PR](https://github.com/huggingface/trl/pull/1235) and sample [colab](https://drive.google.com/file/d/1fSyrSFL9ZyJS69R_lmEW5Hy_Dqi97awt/view?usp=sharing) notebook (I know the implementation isn't right without flash attention but I cant get a running training loop)

The error I get is
```
[/usr/local/lib/python3.10/dist-packages/transformers/trainer.py](https://localhost:8080/#) in compute_loss(self, model, inputs, return_outputs)
   2807         else:
   2808             if isinstance(outputs, dict) and "loss" not in outputs:
-> 2809                 raise ValueError(
   2810                     "The model did not return a loss from the inputs, only the following keys: "
   2811                     f"{','.join(outputs.keys())}. For reference, the inputs it received are {','.join(inputs.keys())}."

ValueError: The model did not return a loss from the inputs, only the following keys: logits. For reference, the inputs it received are input_ids,attention_mask.
```

**Comment by khai-meetkai** [comment]
Hi [nivibilla](https://github.com/nivibilla),
I think there is a bug in your PR, I have just made a comment in your PR: https://github.com/huggingface/trl/pull/1235#discussion_r1457699675
If you fix this as I suggested, you won't run into error any more. And if you run with flash-attention, it will work well. I already tested and saw it working.
Let me know if you have any questions !
